site_name: traces
repo_url: https://github.com/datascopeanalytics/traces/tree/master
theme: readthedocs
site_description: Tools for unevenly-spaced time series data
site_author: Mike Stringer
site_favicon: http://datascopeanalytics.com/static/main/img/favicon.ico
copyright:
extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - smarty
    - mdx_math
pages:
- Home: 'index.md'
- Installation: 'installation.md'
