version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-2.7
jobs:
  test-3.6: &test-template
    docker:
     - image: circleci/python:3.6-jessie
    filters:
      branches:
        only: dev
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv --no-site-packages venv
            . venv/bin/activate
            pip install --quiet -e .[test]
      - save_cache:
          key: deps1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests --with-coverage --cover-package=traces --cover-html --cover-html-dir=/tmp/coverage
            pycodestyle traces/
      - store-artifacts:
          path: /tmp/coverage
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie
